[build]
  publish = "dist"
  command = "npm run build"
[[redirects]]
  from = "https://orizens.com/cv"
  to = "https://orizens.github.io/cv"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''